Add rekt news
thisdot/tech-newsletters pull request #38
Opened 2022-10-07 18:12 UTC by jonasvag

## Adding a tech newsletter
- [x] Suggestion is not a duplicate
- [x] Suggestion is under the proper category
- [x] Name and link to the newsletter is included 
- [x] Name and link are spelled correctly

2022-10-09 16:45 UTC, jonasvag commented
Hello, can this be approved?
https://rekt.news/

2022-10-10 16:54 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-10 16:54 UTC, jdwilkin4 commented on README.md
> +- [Rekt News](https://doshbot.us8.list-manage.com/subscribe?u=4db8948c1d40f1c0e7af494fd&id=798585766e/)
The link you provided is not working.
Let's change it to this one here

```suggestion
- [Rekt News](https://rekt.news/)
```

2022-10-10 17:01 UTC, jonasvag commented
Updated by suggestion

2022-10-10 18:34 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-10 18:35 UTC, merged